package BigBoss;

public enum AbilityType {
	ATTACK_PHYSICAL,
	ATTACK_PHYSICAL_DEFEND,
	ATTACK_PHYSICAL_BUFF,
	ATTACK_PHYSICAL_DEBUFF,
	ATTACK_NON_PHISICAL,
	ATTACK_NON_PHISICAL_DEFEND,
	ATTACK_NON_PHISICAL_BUFF,
	ATTACK_NON_PHISICAL_DEBUFF,
	DEFEND,
	DEFEND_BUFF,
	DEFEND_DEBUFF,
	BUFF,
	DEBUFF,
	BUFF_DEBUFF,
	UNKNOWN
	
}
